#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using GroundStation.model.entity.telerik;

namespace GroundStation.model.entity.telerik	
{
	public partial class SatelliteModelTelerik : OpenAccessContext, ISatelliteModelTelerikUnitOfWork
	{
		private static string connectionStringName = @"ConnectionTelerik";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("SatelliteModelTelerik.rlinq");
		
		public SatelliteModelTelerik()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public SatelliteModelTelerik(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public SatelliteModelTelerik(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public SatelliteModelTelerik(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public SatelliteModelTelerik(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Value_alia> Value_alias 
		{
			get
			{
				return this.GetAll<Value_alia>();
			}
		}
		
		public IQueryable<Telemetry_data_arragment> Telemetry_data_arragments 
		{
			get
			{
				return this.GetAll<Telemetry_data_arragment>();
			}
		}
		
		public IQueryable<Telemetry> Telemetries 
		{
			get
			{
				return this.GetAll<Telemetry>();
			}
		}
		
		public IQueryable<Subsystem_mode> Subsystem_modes 
		{
			get
			{
				return this.GetAll<Subsystem_mode>();
			}
		}
		
		public IQueryable<Subsystem> Subsystems 
		{
			get
			{
				return this.GetAll<Subsystem>();
			}
		}
		
		public IQueryable<Session_operation_list> Session_operation_lists 
		{
			get
			{
				return this.GetAll<Session_operation_list>();
			}
		}
		
		public IQueryable<Parameter> Parameters 
		{
			get
			{
				return this.GetAll<Parameter>();
			}
		}
		
		public IQueryable<Operation_group> Operation_groups 
		{
			get
			{
				return this.GetAll<Operation_group>();
			}
		}
		
		public IQueryable<Modbus_type> Modbus_types 
		{
			get
			{
				return this.GetAll<Modbus_type>();
			}
		}
		
		public IQueryable<Modbus_function> Modbus_functions 
		{
			get
			{
				return this.GetAll<Modbus_function>();
			}
		}
		
		public IQueryable<Log_record> Log_records 
		{
			get
			{
				return this.GetAll<Log_record>();
			}
		}
		
		public IQueryable<Device> Devices 
		{
			get
			{
				return this.GetAll<Device>();
			}
		}
		
		public IQueryable<Cyclogram_property> Cyclogram_properties 
		{
			get
			{
				return this.GetAll<Cyclogram_property>();
			}
		}
		
		public IQueryable<Command_control> Command_controls 
		{
			get
			{
				return this.GetAll<Command_control>();
			}
		}
		
		public IQueryable<Calculation_formula> Calculation_formulas 
		{
			get
			{
				return this.GetAll<Calculation_formula>();
			}
		}
		
		public IQueryable<Alias_group> Alias_groups 
		{
			get
			{
				return this.GetAll<Alias_group>();
			}
		}
		
		public IQueryable<V_session_operation_list_arragment> V_session_operation_list_arragments 
		{
			get
			{
				return this.GetAll<V_session_operation_list_arragment>();
			}
		}
		
		public IQueryable<V_session_operation_list> V_session_operation_lists 
		{
			get
			{
				return this.GetAll<V_session_operation_list>();
			}
		}
		
		public IQueryable<V_session_operation_combo_box> V_session_operation_combo_boxes 
		{
			get
			{
				return this.GetAll<V_session_operation_combo_box>();
			}
		}
		
		public IQueryable<V_parameter> V_parameters 
		{
			get
			{
				return this.GetAll<V_parameter>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "PostgreSql";
			backend.ProviderName = "Npgsql";
			return backend;
		}
	}
	
	public interface ISatelliteModelTelerikUnitOfWork : IUnitOfWork
	{
		IQueryable<Value_alia> Value_alias
		{
			get;
		}
		IQueryable<Telemetry_data_arragment> Telemetry_data_arragments
		{
			get;
		}
		IQueryable<Telemetry> Telemetries
		{
			get;
		}
		IQueryable<Subsystem_mode> Subsystem_modes
		{
			get;
		}
		IQueryable<Subsystem> Subsystems
		{
			get;
		}
		IQueryable<Session_operation_list> Session_operation_lists
		{
			get;
		}
		IQueryable<Parameter> Parameters
		{
			get;
		}
		IQueryable<Operation_group> Operation_groups
		{
			get;
		}
		IQueryable<Modbus_type> Modbus_types
		{
			get;
		}
		IQueryable<Modbus_function> Modbus_functions
		{
			get;
		}
		IQueryable<Log_record> Log_records
		{
			get;
		}
		IQueryable<Device> Devices
		{
			get;
		}
		IQueryable<Cyclogram_property> Cyclogram_properties
		{
			get;
		}
		IQueryable<Command_control> Command_controls
		{
			get;
		}
		IQueryable<Calculation_formula> Calculation_formulas
		{
			get;
		}
		IQueryable<Alias_group> Alias_groups
		{
			get;
		}
		IQueryable<V_session_operation_list_arragment> V_session_operation_list_arragments
		{
			get;
		}
		IQueryable<V_session_operation_list> V_session_operation_lists
		{
			get;
		}
		IQueryable<V_session_operation_combo_box> V_session_operation_combo_boxes
		{
			get;
		}
		IQueryable<V_parameter> V_parameters
		{
			get;
		}
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Value_alia
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _alias_group_id;
		public virtual long? Alias_group_id
		{
			get
			{
				return this._alias_group_id;
			}
			set
			{
				this._alias_group_id = value;
			}
		}
		
		private double? _value;
		public virtual double? Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private string _alias_text;
		public virtual string Alias_text
		{
			get
			{
				return this._alias_text;
			}
			set
			{
				this._alias_text = value;
			}
		}
		
		private string _alias_description;
		public virtual string Alias_description
		{
			get
			{
				return this._alias_description;
			}
			set
			{
				this._alias_description = value;
			}
		}
		
		private Alias_group _alias_group;
		public virtual Alias_group Alias_group
		{
			get
			{
				return this._alias_group;
			}
			set
			{
				this._alias_group = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Telemetry_data_arragment
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _operation_group_id;
		public virtual long? Operation_group_id
		{
			get
			{
				return this._operation_group_id;
			}
			set
			{
				this._operation_group_id = value;
			}
		}
		
		private long? _session_operation_group_id;
		public virtual long? Session_operation_group_id
		{
			get
			{
				return this._session_operation_group_id;
			}
			set
			{
				this._session_operation_group_id = value;
			}
		}
		
		private DateTime? _date;
		public virtual DateTime? Date
		{
			get
			{
				return this._date;
			}
			set
			{
				this._date = value;
			}
		}
		
		private byte[] _data;
		public virtual byte[] Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Telemetry
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private byte[] _pdata;
		public virtual byte[] Pdata
		{
			get
			{
				return this._pdata;
			}
			set
			{
				this._pdata = value;
			}
		}
		
		private DateTime? _pdate;
		public virtual DateTime? Pdate
		{
			get
			{
				return this._pdate;
			}
			set
			{
				this._pdate = value;
			}
		}
		
		private DateTime? _ptime;
		public virtual DateTime? Ptime
		{
			get
			{
				return this._ptime;
			}
			set
			{
				this._ptime = value;
			}
		}
		
		private string _device_msg;
		public virtual string Device_msg
		{
			get
			{
				return this._device_msg;
			}
			set
			{
				this._device_msg = value;
			}
		}
		
		private int? _device_address;
		public virtual int? Device_address
		{
			get
			{
				return this._device_address;
			}
			set
			{
				this._device_address = value;
			}
		}
		
		private int? _status;
		public virtual int? Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Subsystem_mode
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _subsystem_id;
		public virtual int Subsystem_id
		{
			get
			{
				return this._subsystem_id;
			}
			set
			{
				this._subsystem_id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _code;
		public virtual int Code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		
		private string _alias;
		public virtual string Alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				this._alias = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private Subsystem _subsystem;
		public virtual Subsystem Subsystem
		{
			get
			{
				return this._subsystem;
			}
			set
			{
				this._subsystem = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Subsystem
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long _device_id;
		public virtual long Device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				this._device_id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _alias;
		public virtual string Alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				this._alias = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private Device _device;
		public virtual Device Device
		{
			get
			{
				return this._device;
			}
			set
			{
				this._device = value;
			}
		}
		
		private IList<Subsystem_mode> _subsystem_modes = new List<Subsystem_mode>();
		public virtual IList<Subsystem_mode> Subsystem_modes
		{
			get
			{
				return this._subsystem_modes;
			}
		}
		
		private IList<Cyclogram_property> _cyclogram_properties = new List<Cyclogram_property>();
		public virtual IList<Cyclogram_property> Cyclogram_properties
		{
			get
			{
				return this._cyclogram_properties;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Session_operation_list
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _parameter_id;
		public virtual long? Parameter_id
		{
			get
			{
				return this._parameter_id;
			}
			set
			{
				this._parameter_id = value;
			}
		}
		
		private long? _operation_group_id;
		public virtual long? Operation_group_id
		{
			get
			{
				return this._operation_group_id;
			}
			set
			{
				this._operation_group_id = value;
			}
		}
		
		private long? _type;
		public virtual long? Type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		
		private long? _value;
		public virtual long? Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private long _priority;
		public virtual long Priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		
		private short? _command_control_type;
		public virtual short? Command_control_type
		{
			get
			{
				return this._command_control_type;
			}
			set
			{
				this._command_control_type = value;
			}
		}
		
		private bool? _is_not_arragment;
		public virtual bool? Is_not_arragment
		{
			get
			{
				return this._is_not_arragment;
			}
			set
			{
				this._is_not_arragment = value;
			}
		}
		
		private Operation_group _operation_group;
		public virtual Operation_group Operation_group
		{
			get
			{
				return this._operation_group;
			}
			set
			{
				this._operation_group = value;
			}
		}
		
		private Parameter _parameter;
		public virtual Parameter Parameter
		{
			get
			{
				return this._parameter;
			}
			set
			{
				this._parameter = value;
			}
		}
		
		private IList<Command_control> _command_controls = new List<Command_control>();
		public virtual IList<Command_control> Command_controls
		{
			get
			{
				return this._command_controls;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Parameter
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _calculation_formula_id;
		public virtual long? Calculation_formula_id
		{
			get
			{
				return this._calculation_formula_id;
			}
			set
			{
				this._calculation_formula_id = value;
			}
		}
		
		private long _device_id;
		public virtual long Device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				this._device_id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private long? _register_address_start;
		public virtual long? Register_address_start
		{
			get
			{
				return this._register_address_start;
			}
			set
			{
				this._register_address_start = value;
			}
		}
		
		private short? _access;
		public virtual short? Access
		{
			get
			{
				return this._access;
			}
			set
			{
				this._access = value;
			}
		}
		
		private long? _modbus_type_id;
		public virtual long? Modbus_type_id
		{
			get
			{
				return this._modbus_type_id;
			}
			set
			{
				this._modbus_type_id = value;
			}
		}
		
		private double? _min_value;
		public virtual double? Min_value
		{
			get
			{
				return this._min_value;
			}
			set
			{
				this._min_value = value;
			}
		}
		
		private double? _max_value;
		public virtual double? Max_value
		{
			get
			{
				return this._max_value;
			}
			set
			{
				this._max_value = value;
			}
		}
		
		private long? _alias_group_id;
		public virtual long? Alias_group_id
		{
			get
			{
				return this._alias_group_id;
			}
			set
			{
				this._alias_group_id = value;
			}
		}
		
		private short? _start_bit;
		public virtual short? Start_bit
		{
			get
			{
				return this._start_bit;
			}
			set
			{
				this._start_bit = value;
			}
		}
		
		private short? _end_bit;
		public virtual short? End_bit
		{
			get
			{
				return this._end_bit;
			}
			set
			{
				this._end_bit = value;
			}
		}
		
		private Device _device;
		public virtual Device Device
		{
			get
			{
				return this._device;
			}
			set
			{
				this._device = value;
			}
		}
		
		private IList<Session_operation_list> _session_operation_lists = new List<Session_operation_list>();
		public virtual IList<Session_operation_list> Session_operation_lists
		{
			get
			{
				return this._session_operation_lists;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Operation_group
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private DateTime? _created_at;
		public virtual DateTime? Created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				this._created_at = value;
			}
		}
		
		private IList<Session_operation_list> _session_operation_lists = new List<Session_operation_list>();
		public virtual IList<Session_operation_list> Session_operation_lists
		{
			get
			{
				return this._session_operation_lists;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Modbus_type
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private short? _modbus_register_count;
		public virtual short? Modbus_register_count
		{
			get
			{
				return this._modbus_register_count;
			}
			set
			{
				this._modbus_register_count = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Modbus_function
	{
		private short _id;
		public virtual short Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private short? _code;
		public virtual short? Code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Log_record
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime? _date;
		public virtual DateTime? Date
		{
			get
			{
				return this._date;
			}
			set
			{
				this._date = value;
			}
		}
		
		private string _message;
		public virtual string Message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		
		private long? _device_id;
		public virtual long? Device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				this._device_id = value;
			}
		}
		
		private short? _type;
		public virtual short? Type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Device
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private short? _modbus_address;
		public virtual short? Modbus_address
		{
			get
			{
				return this._modbus_address;
			}
			set
			{
				this._modbus_address = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private IList<Subsystem> _subsystems = new List<Subsystem>();
		public virtual IList<Subsystem> Subsystems
		{
			get
			{
				return this._subsystems;
			}
		}
		
		private IList<Parameter> _parameters = new List<Parameter>();
		public virtual IList<Parameter> Parameters
		{
			get
			{
				return this._parameters;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Cyclogram_property
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _subsystem_id;
		public virtual int Subsystem_id
		{
			get
			{
				return this._subsystem_id;
			}
			set
			{
				this._subsystem_id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _modbus_start_address;
		public virtual int Modbus_start_address
		{
			get
			{
				return this._modbus_start_address;
			}
			set
			{
				this._modbus_start_address = value;
			}
		}
		
		private int _cmnd_reg_count;
		public virtual int Cmnd_reg_count
		{
			get
			{
				return this._cmnd_reg_count;
			}
			set
			{
				this._cmnd_reg_count = value;
			}
		}
		
		private int _start_date_time_reg_count;
		public virtual int Start_date_time_reg_count
		{
			get
			{
				return this._start_date_time_reg_count;
			}
			set
			{
				this._start_date_time_reg_count = value;
			}
		}
		
		private int _code_size_reg_count;
		public virtual int Code_size_reg_count
		{
			get
			{
				return this._code_size_reg_count;
			}
			set
			{
				this._code_size_reg_count = value;
			}
		}
		
		private int _code_reg_count;
		public virtual int Code_reg_count
		{
			get
			{
				return this._code_reg_count;
			}
			set
			{
				this._code_reg_count = value;
			}
		}
		
		private int _crc32_reg_count;
		public virtual int Crc32_reg_count
		{
			get
			{
				return this._crc32_reg_count;
			}
			set
			{
				this._crc32_reg_count = value;
			}
		}
		
		private Subsystem _subsystem;
		public virtual Subsystem Subsystem
		{
			get
			{
				return this._subsystem;
			}
			set
			{
				this._subsystem = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Command_control
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _session_operation_id;
		public virtual long? Session_operation_id
		{
			get
			{
				return this._session_operation_id;
			}
			set
			{
				this._session_operation_id = value;
			}
		}
		
		private string _hot_key;
		public virtual string Hot_key
		{
			get
			{
				return this._hot_key;
			}
			set
			{
				this._hot_key = value;
			}
		}
		
		private long? _next_session_operation_id;
		public virtual long? Next_session_operation_id
		{
			get
			{
				return this._next_session_operation_id;
			}
			set
			{
				this._next_session_operation_id = value;
			}
		}
		
		private short? _show_dialog_type;
		public virtual short? Show_dialog_type
		{
			get
			{
				return this._show_dialog_type;
			}
			set
			{
				this._show_dialog_type = value;
			}
		}
		
		private long? _show_dialog_time;
		public virtual long? Show_dialog_time
		{
			get
			{
				return this._show_dialog_time;
			}
			set
			{
				this._show_dialog_time = value;
			}
		}
		
		private string _expression;
		public virtual string Expression
		{
			get
			{
				return this._expression;
			}
			set
			{
				this._expression = value;
			}
		}
		
		private Session_operation_list _session_operation_list;
		public virtual Session_operation_list Session_operation_list
		{
			get
			{
				return this._session_operation_list;
			}
			set
			{
				this._session_operation_list = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Calculation_formula
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _si_unit_name;
		public virtual string Si_unit_name
		{
			get
			{
				return this._si_unit_name;
			}
			set
			{
				this._si_unit_name = value;
			}
		}
		
		private string _formula;
		public virtual string Formula
		{
			get
			{
				return this._formula;
			}
			set
			{
				this._formula = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class Alias_group
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private IList<Value_alia> _value_alias = new List<Value_alia>();
		public virtual IList<Value_alia> Value_alias
		{
			get
			{
				return this._value_alias;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class V_session_operation_list_arragment
	{
		private long _session_operation_list_id;
		public virtual long Session_operation_list_id
		{
			get
			{
				return this._session_operation_list_id;
			}
			set
			{
				this._session_operation_list_id = value;
			}
		}
		
		private long? _operation_group_id;
		public virtual long? Operation_group_id
		{
			get
			{
				return this._operation_group_id;
			}
			set
			{
				this._operation_group_id = value;
			}
		}
		
		private long? _parameter_id;
		public virtual long? Parameter_id
		{
			get
			{
				return this._parameter_id;
			}
			set
			{
				this._parameter_id = value;
			}
		}
		
		private long? _priority;
		public virtual long? Priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		
		private short? _command_control_type;
		public virtual short? Command_control_type
		{
			get
			{
				return this._command_control_type;
			}
			set
			{
				this._command_control_type = value;
			}
		}
		
		private short? _modbus_address;
		public virtual short? Modbus_address
		{
			get
			{
				return this._modbus_address;
			}
			set
			{
				this._modbus_address = value;
			}
		}
		
		private long? _alias_group_id;
		public virtual long? Alias_group_id
		{
			get
			{
				return this._alias_group_id;
			}
			set
			{
				this._alias_group_id = value;
			}
		}
		
		private string _alias_group_name;
		public virtual string Alias_group_name
		{
			get
			{
				return this._alias_group_name;
			}
			set
			{
				this._alias_group_name = value;
			}
		}
		
		private long? _register_address_start;
		public virtual long? Register_address_start
		{
			get
			{
				return this._register_address_start;
			}
			set
			{
				this._register_address_start = value;
			}
		}
		
		private short? _start_bit;
		public virtual short? Start_bit
		{
			get
			{
				return this._start_bit;
			}
			set
			{
				this._start_bit = value;
			}
		}
		
		private short? _end_bit;
		public virtual short? End_bit
		{
			get
			{
				return this._end_bit;
			}
			set
			{
				this._end_bit = value;
			}
		}
		
		private short? _modbus_register_count;
		public virtual short? Modbus_register_count
		{
			get
			{
				return this._modbus_register_count;
			}
			set
			{
				this._modbus_register_count = value;
			}
		}
		
		private short? _access;
		public virtual short? Access
		{
			get
			{
				return this._access;
			}
			set
			{
				this._access = value;
			}
		}
		
		private string _device_name;
		public virtual string Device_name
		{
			get
			{
				return this._device_name;
			}
			set
			{
				this._device_name = value;
			}
		}
		
		private string _parameter_name;
		public virtual string Parameter_name
		{
			get
			{
				return this._parameter_name;
			}
			set
			{
				this._parameter_name = value;
			}
		}
		
		private string _type;
		public virtual string Type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		
		private long? _value;
		public virtual long? Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private bool? _is_not_arragment;
		public virtual bool? Is_not_arragment
		{
			get
			{
				return this._is_not_arragment;
			}
			set
			{
				this._is_not_arragment = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class V_session_operation_list
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _priority;
		public virtual long? Priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		
		private short? _command_control_type;
		public virtual short? Command_control_type
		{
			get
			{
				return this._command_control_type;
			}
			set
			{
				this._command_control_type = value;
			}
		}
		
		private long? _operation_group_id;
		public virtual long? Operation_group_id
		{
			get
			{
				return this._operation_group_id;
			}
			set
			{
				this._operation_group_id = value;
			}
		}
		
		private string _device_name;
		public virtual string Device_name
		{
			get
			{
				return this._device_name;
			}
			set
			{
				this._device_name = value;
			}
		}
		
		private string _parameter_name;
		public virtual string Parameter_name
		{
			get
			{
				return this._parameter_name;
			}
			set
			{
				this._parameter_name = value;
			}
		}
		
		private string _type;
		public virtual string Type
		{
			get
			{
				return this._type;
			}
			set
			{
				this._type = value;
			}
		}
		
		private long? _value;
		public virtual long? Value
		{
			get
			{
				return this._value;
			}
			set
			{
				this._value = value;
			}
		}
		
		private bool? _is_not_arragment;
		public virtual bool? Is_not_arragment
		{
			get
			{
				return this._is_not_arragment;
			}
			set
			{
				this._is_not_arragment = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class V_session_operation_combo_box
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _operation_group_id;
		public virtual long? Operation_group_id
		{
			get
			{
				return this._operation_group_id;
			}
			set
			{
				this._operation_group_id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
	}
}
namespace GroundStation.model.entity.telerik	
{
	public partial class V_parameter
	{
		private long _id;
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private long? _calculation_formula_id;
		public virtual long? Calculation_formula_id
		{
			get
			{
				return this._calculation_formula_id;
			}
			set
			{
				this._calculation_formula_id = value;
			}
		}
		
		private long? _device_id;
		public virtual long? Device_id
		{
			get
			{
				return this._device_id;
			}
			set
			{
				this._device_id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private long? _register_address_start;
		public virtual long? Register_address_start
		{
			get
			{
				return this._register_address_start;
			}
			set
			{
				this._register_address_start = value;
			}
		}
		
		private short? _access;
		public virtual short? Access
		{
			get
			{
				return this._access;
			}
			set
			{
				this._access = value;
			}
		}
		
		private string _access_name;
		public virtual string Access_name
		{
			get
			{
				return this._access_name;
			}
			set
			{
				this._access_name = value;
			}
		}
		
		private long? _modbus_type_id;
		public virtual long? Modbus_type_id
		{
			get
			{
				return this._modbus_type_id;
			}
			set
			{
				this._modbus_type_id = value;
			}
		}
		
		private string _modbus_type_name;
		public virtual string Modbus_type_name
		{
			get
			{
				return this._modbus_type_name;
			}
			set
			{
				this._modbus_type_name = value;
			}
		}
		
		private double? _min_value;
		public virtual double? Min_value
		{
			get
			{
				return this._min_value;
			}
			set
			{
				this._min_value = value;
			}
		}
		
		private double? _max_value;
		public virtual double? Max_value
		{
			get
			{
				return this._max_value;
			}
			set
			{
				this._max_value = value;
			}
		}
		
	}
}
#pragma warning restore 1591
