///////////////////////////////////////////////////////////
//  operation_group.cs
//  Implementation of the Class operation_group
//  Generated by Enterprise Architect
//  Created on:      16-фев-2013 16:43:27
//  Original author: Ostrovskiy Ihor
///////////////////////////////////////////////////////////
using System.Data;
using System;
using Npgsql;
using log4net;
using log4net.Config;
using System.Collections.Generic;
using GroundStation.model.entity.telerik;
using System.Linq;

namespace controller {
	/// <summary>
	/// Групи операцій для індевідуального сеансу звязку
	/// </summary>
	public class AliasManager {

        public static readonly ILog log = LogManager.GetLogger(typeof(AliasManager));
        private DataSet ds = new DataSet();
        NpgsqlDataAdapter da;        
	

        public DataTable getAliasGroup()
        {
            NpgsqlConnection conn = ConnectionManager.getConnection();
            try
            {
                string sql = "SELECT * FROM alias_group order by id ASC";                
                da = new NpgsqlDataAdapter(sql, conn);                
                ds.Reset();                
                da.Fill(ds);               
                //ds.Tables[0].Columns["name"].ColumnName = "Назва групи псевдонімів";
                //ds.Tables[0].Columns["description"].ColumnName = "Опис групи псевдонімів";                
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                log.Error(e.Message, e);
            }
            finally
            {
                if (conn != null)
                    conn.Close();
            }
            return null;
        }

        public List<Alias_group> getAliasGroupList()
        {
            try
            {
                return ConnectionManager.getEntities().Alias_groups.ToList();
            }
            catch (Exception e)
            {
                log.Error(e.Message, e);
            }
            return null;         
        }

        public DataTable getValueAliasDataTableByGroupId(int _id)
        {
            NpgsqlConnection conn = ConnectionManager.getConnection();
            try
            {
                string sql = "SELECT * FROM value_alias WHERE alias_group_id=" + _id + " order by value";
                da = new NpgsqlDataAdapter(sql, conn);                
                
                ds.Reset();
                da.Fill(ds);              
                //ds.Tables[0].Columns["name"].ColumnName = "Назва групи псевдонімів";
                //ds.Tables[0].Columns["description"].ColumnName = "Опис групи псевдонімів";
                return ds.Tables[0];
            }
            catch (Exception e)
            {
                log.Error(e.Message, e);
            }   
            finally
            {
                if (conn != null)
                    conn.Close();
            }
            return null;
        }


        public List<Value_alia> getValueAliasListByGroupId(int _id)
        {
            try
            {
                return ConnectionManager.getEntities().Value_alias.Where(c => c.Alias_group_id == _id).ToList();
            }
            catch (Exception e)
            {
                log.Error(e.Message, e);
            }
            return null; 
        }       
    }
}