///////////////////////////////////////////////////////////
//  calculation_formula.cs
//  Implementation of the Class calculation_formula
//  Generated by Enterprise Architect
//  Created on:      16-фев-2013 16:44:12
//  Original author: Ostrovskiy Ihor
///////////////////////////////////////////////////////////

using System;

namespace controller {
	/// <summary>
	/// Таблиця з формулами переводу в інженерні велечини параметрів
	/// </summary>
	public class CalculationFormulaManager {		

    }//end CalculationFormula

}//end namespace GraundStationDB