///////////////////////////////////////////////////////////
//  log_record.cs
//  Implementation of the Class log_record
//  Generated by Enterprise Architect
//  Created on:      16-фев-2013 16:42:21
//  Original author: Ostrovskiy Ihor
///////////////////////////////////////////////////////////
using System;

namespace controller {
	/// <summary>
	/// Таблиця логування подій
	/// </summary>
	public class LogRecordManager {

		/// <summary>
		/// Ідентифікатор запису
		/// </summary>
		public int id;
		/// <summary>
		/// Дата винекненої події
		/// </summary>
		public DateTime date;
		/// <summary>
		/// Опис події
		/// </summary>
		public string message;
		/// <summary>
		/// Якщо подія повязана з певною підсистемою, вказується ідентифікатор системи
		/// </summary>
		public int device_id;
		/// <summary>
		/// Тип події (error - повилка, info - інформаційни запис, exception - запис
		/// вийняткової ситуації)
		/// </summary>
		public int type;

		public LogRecordManager(){

		}

		~LogRecordManager(){

		}

		public virtual void Dispose(){

		}
    }//end LogRecord

}//end namespace GraundStationDB